version: '3'
services:
  fullstack-mysql:
    image: mysql:5.7
    container_name: full_db_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - fullstack

  app:
    container_name: full_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - fullstack-mysql
    networks:
      - fullstack
networks:
  fullstack:
    driver: bridge
