version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - mysql-db
    networks:
      - database


  mysql-db:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - 3307:3307
    environment:
      - MYSQL_ROOT_HOST=${DBHost}
      - MYSQL_USER=${DBUser}
      - MYSQL_PASSWORD=${DBPass}
      - MYSQL_DATABASE=${DBName}
      - MYSQL_ROOT_PASSWORD=${DBPass}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - database

volumes:
  api:
  database_mysql:

networks:
  database:
    driver: bridge
